//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Solutions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int Request_Number { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public Nullable<int> Equipment_ID { get; set; }
        public string Issue_Type { get; set; }
        public string Issue_Description { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public string Request_Status { get; set; }
        public Nullable<System.DateTime> Response_Date { get; set; }
        public string Response { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Users Users { get; set; }
    }
}
